# Generated by Django 5.1.7 on 2025-04-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_users_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="last_login",
        ),
    ]
