# Generated by Django 5.1.7 on 2025-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.TextField(max_length=150, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.TextField(max_length=150, verbose_name="Surname"),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.TextField(max_length=20, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.TextField(
                max_length=150, unique=True, verbose_name="Username"
            ),
        ),
    ]
