# Generated by Django 5.1.7 on 2025-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.TextField(blank=True, max_length=20, verbose_name="Password"),
        ),
    ]
