# Generated by Django 5.1.7 on 2025-06-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_users_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.TextField(max_length=20, verbose_name="Password"),
        ),
    ]
