# Generated by Django 5.1.7 on 2025-04-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_users_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
