# Generated by Django 5.1.7 on 2025-06-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_users_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="updated_at",
        ),
    ]
