# Generated by Django 5.1.7 on 2025-06-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=150, verbose_name="Name")),
                (
                    "author",
                    models.TextField(
                        blank=True, max_length=150, null=True, verbose_name="Author"
                    ),
                ),
                (
                    "discription",
                    models.TextField(max_length=100, verbose_name="discription"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
            ],
        ),
    ]
