# Generated by Django 5.1.7 on 2025-06-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="label",
            new_name="labels",
        ),
    ]
