# Generated by Django 5.1.7 on 2025-04-24 14:16

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_tasks_author_tasks_executor"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="tasks",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
