# Generated by Django 5.1.7 on 2025-04-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_tasks_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="tasks",
            managers=[],
        ),
    ]
