# Generated by Django 5.1.7 on 2025-04-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_tasks_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="author",
            field=models.TextField(
                max_length=150, null=True, unique=True, verbose_name="Author"
            ),
        ),
    ]
