# Generated by Django 5.1.7 on 2025-04-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_tasks_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="author",
            field=models.TextField(max_length=150, null=True, verbose_name="Author"),
        ),
    ]
