# Generated by Django 5.1.7 on 2025-04-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_tasks_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="discription",
            field=models.TextField(max_length=100, verbose_name="discription"),
        ),
    ]
