# Generated by Django 5.1.7 on 2025-05-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0009_alter_tasks_author_alter_tasks_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="label",
            field=models.ManyToManyField(
                blank=True, to="labels.labels", verbose_name="Labels"
            ),
        ),
    ]
