# Generated by Django 4.2.20 on 2025-06-03 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0010_alter_tasks_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executor",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="statuses.statuses",
                verbose_name="Status",
            ),
        ),
    ]
