# Generated by Django 5.1.7 on 2025-06-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_alter_tasks_executor_alter_tasks_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="updated_at",
        ),
    ]
