# Generated by Django 5.1.7 on 2025-06-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statuses",
            name="updated_at",
        ),
    ]
